### ISSUE TITLE
Players abuse infinite time Glitch so they never give up their turn 

### ISSUE THREAD

**Issue by cSikorsky** [shishkabob27/CardWarsKingdom-Issues#6] opened 2024-01-25 00:49 UTC
**Describe the bug**

**To Reproduce**
After you give your opponent the turn, he does something, I don't know if it's an external program or it freezes the game, I don't know... The fact is that it freezes time so that he never gives the turn back.

With this they ensure that the 15 seconds to give up the turn do not appear and they hope that you give up so that they can achieve an easy victory

**Smartphone (please complete the following information):**
 - Device: POCO F4 GT
 - OS: ANDROID 12
 - Version 1.0.17

**Additional context**
This has already happened to me several times in PvP and in the past, they also used this dirty trick or Glitch to win by cheating, the one who abused the Glitch this time is called Kirito (Rank 8 in PvP)
I spent 8 minutes waiting for the turn to give up and my reaction was to give up, I couldn't do anything else

![IMG_20240201_014901](https://github.com/shishkabob27/CardWarsKingdom-Issues/assets/157223796/08879ba0-671d-4e52-ac5d-1b1eb56d2d02)

**Comment by shishkabob27** [comment] 2024-02-01 16:27
Duplicate of #4 ?

**Comment by cSikorsky** [comment] 2024-02-01 18:12
Yes, I'm sorry, I think I got so angry that I forgot to report this same bug the other time.

**Comment by cSikorsky** [comment] 2024-02-01 18:12
Yes, I'm sorry, I think I got so angry that I forgot to report this same bug the other time.

**Closed as completed** 2024-02-01 18:17 UTC
Labels: duplicate
