### ISSUE TITLE
AFK Glitch in PvP

### ISSUE THREAD

**Issue by CARDWARSKINGDOM** [shishkabob27/CardWarsKingdom-Issues#8] opened 2024-01-25 16:15 UTC
I don't really know how to do this glitch and how it Can be done but
Basicly your turn never ends in a PvP match causes Ur opponent to just quit and means a free win
This should be fixed asap cause you Can litterly reach rank 1 using that Glitch

**Comment by shishkabob27** [comment] 2024-02-01 18:18
Duplicate of #4

**Closed as completed** 2024-02-01 18:18 UTC
Labels: duplicate
